const menu=document.querySelector('.menu'),nav=document.querySelector('nav');
menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));});
nav?.addEventListener('click',e=>{if(e.target.closest('a')){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');}});
const formatDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(value||'')?value.split('-').reverse().join('. '):value;
const form=document.querySelector('#application'),out=document.querySelector('#print-area');
const officialParagraphs=["PRIHLÁŠKA ZA ČLENA / ČLENKU ODBOROVEJ ORGANIZÁCIE", "Základná odborová organizácia pri Packeta Slovakia s. r. o.", "1. Osobné údaje žiadateľa / žiadateľky", "Meno a priezvisko, titul", "Dátum narodenia", "Adresa trvalého bydliska", "Telefón", "E-mail", "Pracovné zaradenie / útvar", "Osobné číslo zamestnanca (ak je pridelené)", "Dátum nástupu do zamestnania u Packeta Slovakia s. r. o.", "2. Vyhlásenie žiadateľa / žiadateľky", "Žiadam o prijatie za člena / členku Základnej odborovej organizácie pri Packeta Slovakia s. r. o. (ďalej len „odborová organizácia“). Vyhlasujem, že som sa oboznámil(a) so stanovami odborovej organizácie, súhlasím s ich obsahom a zaväzujem sa dodržiavať stanovy a uznesenia orgánov odborovej organizácie, ako aj platiť členské príspevky vo výške a spôsobom určeným členskou schôdzou.", "3. Spôsob úhrady členského príspevku", "Poznámka: Výška členského príspevku k dnešnému dňu ešte nebola určená. O jej výške rozhodne členská schôdza a bude členom vopred oznámená; do toho času sa členské príspevky nevyberajú.", "☐ bankovým prevodom na účet odborovej organizácie", "☐ zrážkou zo mzdy u zamestnávateľa", "V prípade zvolenia úhrady zrážkou zo mzdy udeľujem týmto zamestnávateľovi v súlade s § 131 Zákonníka práce svoj písomný súhlas so zrážaním členského príspevku vo výške určenej členskou schôdzou z mojej mzdy a s jeho poukazovaním v prospech účtu odborovej organizácie. Tento súhlas môžem kedykoľvek písomne odvolať.", "4. Súhlas so spracúvaním osobných údajov", "Súhlasím so spracúvaním svojich osobných údajov uvedených v tejto prihláške odborovou organizáciou, a to za účelom vedenia evidencie členov, zastupovania mojich pracovnoprávnych záujmov a komunikácie s členmi, po celý čas trvania môjho členstva a po dobu vyplývajúcu z osobitných predpisov po jeho skončení. Beriem na vedomie, že moje osobné údaje sa zamestnávateľovi neposkytujú, s výnimkou prípadu, ak sa stanem členom odborového orgánu (výboru), kedy sa moje meno a kontaktné údaje oznamujú zamestnávateľovi v zmysle § 230 ods. 1 Zákonníka práce.", "V _______________________, dňa _______________________", "_______________________________", "podpis žiadateľa / žiadateľky", "Prihlášku po vyplnení odovzdajte niektorému z členov výboru odborovej organizácie osobne alebo ju zašlite na kontaktnú e-mailovú adresu odborovej organizácie.", "Rozhodnutie výboru odborovej organizácie o prijatí za člena", "☐ Žiadateľ / žiadateľka bol(a) prijatý(á) za člena / členku odborovej organizácie dňa: _______________________", "☐ Žiadosť nebola schválená z dôvodu: _______________________________________________", "_______________________________", "predseda / poverený člen výboru odborovej organizácie"];
form?.addEventListener('submit',e=>{
 e.preventDefault();out.replaceChildren();const data=new FormData(form);
 const add=(tag,text)=>{const el=document.createElement(tag);el.textContent=text;out.append(el);return el;};
 for(const [i,source] of officialParagraphs.entries()){
  if(i===3){const table=document.createElement('table');table.className='application-table';for(const label of officialParagraphs.slice(3,11)){const tr=document.createElement('tr');for(const text of [label,(label.startsWith('Dátum')?formatDate(data.get(label)):data.get(label))||'']){const td=document.createElement('td');td.textContent=text;tr.append(td);}table.append(tr);}out.append(table);}
  if(i>=3&&i<=10)continue;
  let text=source;
  if(source.startsWith('☐ bankovým')&&data.get('Spôsob úhrady')==='Bankovým prevodom')text=source.replace('☐','☒');
  if(source.startsWith('☐ zrážkou')&&data.get('Spôsob úhrady')==='Zrážkou zo mzdy')text=source.replace('☐','☒');
  if(source.startsWith('V __________________'))text='V '+(data.get('Miesto podpisu')||'_______________________')+', dňa '+(formatDate(data.get('Dátum podpisu'))||'_______________________');
  add(i===0?'h1':(/^\d\. /.test(source)||source.startsWith('Rozhodnutie výboru')?'h2':'p'),text);
 }
 document.querySelector('#form-status').textContent='Oficiálna prihláška je pripravená na tlač. Nič sa neodoslalo.';window.print();
});
form?.addEventListener('reset',()=>{out.replaceChildren();document.querySelector('#form-status').textContent='Údaje boli vymazané.';});
window.addEventListener('pagehide',()=>{form?.reset();out?.replaceChildren();});
window.addEventListener('pageshow',e=>{if(e.persisted){form?.reset();out?.replaceChildren();}});
document.querySelector('#application-fields')?.removeAttribute('disabled');
