import {readFile,writeFile,mkdir} from 'node:fs/promises';
const src=await readFile('odborovy-asistent-web/knowledge-base.js','utf8');
const base=JSON.parse(src.slice(src.indexOf(' = ')+3).trim().replace(/;$/,''));
await mkdir('ai',{recursive:true});
await writeFile('ai/knowledge.mjs','// Generated by scripts/build-ai.mjs; edit the source knowledge-base.js.\nexport default '+JSON.stringify(base)+';\n');
const engine=await readFile('odborovy-asistent-web/legal-engine.js','utf8');
await writeFile('ai/legal-engine.mjs','// Generated by scripts/build-ai.mjs.\nconst root={};\n'+engine.replace("typeof window !== 'undefined' ? window : globalThis",'root')+'\nexport default root.ODBORACIK_LEGAL_ENGINE;\n');
