/*
  Verejná základná znalostná báza Odboráčika.
  Obsahuje len všeobecné, bezpečné odpovede. Konkrétny pracovný prípad,
  individuálne lehoty, zmluvy a citlivé údaje vždy smerujú na odbory.
*/
window.ODBORACIK_KNOWLEDGE_BASE = [
  { keywords: /čo robia|kto sú odbory|odborová organizácia|úloha odbor/, answer: 'Odbory zastupujú zamestnancov v pracovných témach, zbierajú podnety, kontrolujú dodržiavanie pravidiel a rokujú so zamestnávateľom. Pri konkrétnom prípade môžu pomôcť určiť ďalší krok.' },
  { keywords: /pridať|členstv|vstúpiť|stať sa člen/, answer: 'O členstve, prihlásení a členských otázkach odpovedajú odbory priamo. Použite formulár a vyberte tému „Členstvo alebo spolupráca“.', contact: true },
  { keywords: /dôver|anonym|taj|utaj/, answer: 'Citlivé údaje nepíšte do chatu. Pri osobnom prípade použite formulár a kontaktný e-mail, ku ktorému máte bezpečný prístup. Odboráčik neukladá text vašich správ.' },
  { keywords: /osobné údaje|gdpr|rodné číslo|členský zoznam|súkrom/, answer: 'Členstvo v odboroch a zdravotné údaje sú citlivé. Do chatu ani bežného formulára neposielajte rodné číslo, heslá, úplný personálny spis ani zdravotnú dokumentáciu. Pri potrebe podkladov s vami odbory dohodnú bezpečný spôsob.' },
  { keywords: /pracovná zmluva|zmluva|dodatok|zmeniť mi zmluvu|zmena podmien/, answer: 'Pracovnú zmluvu, dodatok ani zmenu pracovných podmienok nepodpisujte pod nátlakom. Pred podpisom si vyžiadajte čas na prečítanie a pošlite odborom text alebo jeho bezpečne redigovaný opis.', contact: true },
  { keywords: /mzda|výplata|výplatná páska|nevyplat|zrážka zo mzdy|strhli mi/, answer: 'Uschovajte výplatné pásky, evidenciu času a komunikáciu. Pri mzde je dôležité, čo hovorí zmluva, mzdový predpis alebo kolektívna zmluva, preto pošlite odborom dátumy a stručný opis.', contact: true },
  { keywords: /nadčas|práca navyše|overtime/, answer: 'Zapisujte si skutočne odpracovaný čas, zmeny a pokyny na prácu navyše. Posúdenie nadčasu závisí od rozvrhu, evidencie a konkrétneho pracovného vzťahu; odbory preveria podklady.', contact: true },
  { keywords: /pracovn[ýy] čas|zmen|smennosť|rozvrh|prestávk|odpočin/, answer: 'Pri pracovnom čase si uchovajte rozpis zmien, zmeny rozvrhu a vlastnú evidenciu odpracovaného času. Ak zmena zasahuje do života alebo odpočinku, opíšte odborom konkrétne dátumy a spôsob oznámenia.', contact: true },
  { keywords: /dovolenk|voľno|nepustia ma|schváliť dovolenk/, answer: 'Dovolenku a pracovné voľno treba posudzovať podľa konkrétneho nároku, rozvrhu a dohôd na pracovisku. Zapíšte si, kedy ste o voľno požiadali a akú odpoveď ste dostali.', contact: true },
  { keywords: /pn|práceneschop|chorob|zdravot|lekársky posudok/, answer: 'Zdravotné údaje neposielajte do chatu. Ak sa vec týka práce počas PN, preradenia alebo zdravotnej spôsobilosti, kontaktujte odbory a pošlite len minimum potrebných informácií bezpečným spôsobom.', contact: true },
  { keywords: /dohoda|brigáda|dohodár|dohoda o práci/, answer: 'Aj pri dohode sú dôležité jej presné podmienky, rozsah práce, odmena a spôsob skončenia. Pošlite odborom typ dohody, dátumy a opis problému; nemusíte do formulára prikladať celý dokument.', contact: true },
  { keywords: /výpoveď|okamžité skončenie|končí mi|prepúšť|dohoda o skončení|odstupn/, answer: 'Pri skončení pracovného pomeru môžu byť lehoty krátke. Dokument nepodpisujte pod nátlakom, uschovajte originál alebo fotku, zapíšte dátum doručenia a kontaktujte odbory čo najskôr.', contact: true },
  { keywords: /doba určitá|na určitú dobu|predĺženie zmluv/, answer: 'Pri pracovnom pomere na určitú dobu rozhoduje presné znenie zmluvy a okolnosti predĺženia alebo skončenia. Pošlite odborom dátum začiatku, dátum skončenia a relevantnú komunikáciu.', contact: true },
  { keywords: /hromadné prepúšť|rušenie pracoviska|organizačná zmena/, answer: 'Pri hromadnom prepúšťaní a organizačných zmenách má byť priestor na informovanie a prerokovanie so zástupcami zamestnancov. Nešírte neoverené zoznamy; odborom pošlite zdroj informácie, dátum a dosah na pracovisko.', contact: true },
  { keywords: /šikana|bossing|mobbing|poniž|vyhráž|nátlak/, answer: 'Zaznamenajte si dátumy, konkrétne výroky alebo kroky, svedkov a súvisiacu komunikáciu. Do chatu nedávajte mená ani citlivé prílohy. Odbory vám pomôžu určiť bezpečný postup.', contact: true },
  { keywords: /diskrimin|nerovnak|tehot|materstvo|otcov|vek|zdravotné postihnut/, answer: 'Nerovnaké zaobchádzanie treba posudzovať podľa konkrétnych porovnateľných situácií a dôkazov. Zapíšte si, čo sa stalo, kedy a s kým sa prípad porovnáva; kontaktujte odbory čo najskôr.', contact: true },
  { keywords: /odveta|postih za odbory|bojím sa|strach|trestajú ma/, answer: 'Zapíšte si udalosti, dátumy a komunikáciu. Nezdieľajte citlivé detaily vo verejnom chate. Ak sa obávate odvety pre odborovú činnosť alebo podnet, kontaktujte odbory priamo.', contact: true },
  { keywords: /bezpeč|bozp|nebezpeč|úraz|ochranné pomôcky|riziko/, answer: 'Pri bezprostrednom ohrození života alebo zdravia volajte 112. Pracovné riziko nahláste nadriadenému podľa pravidiel pracoviska, zdokumentujte ho primerane a kontaktujte odbory. Pri úraze alebo vážnom riziku nečakajte.', contact: true },
  { keywords: /inšpektorát|inšpekcia práce|podnet na inšpektorát/, answer: 'Inšpektorát práce rieši dodržiavanie pracovnoprávnych predpisov a BOZP. Pred podnetom si uložte fakty, dátumy, podklady a cieľ. Odbory môžu pomôcť vybrať vhodný postup; podnet nenahrádza všetky individuálne lehoty.', contact: true },
  { keywords: /kamera|sledov|monitorovanie|gps|kontrola zamestnancov/, answer: 'Monitorovanie na pracovisku môže zasahovať do súkromia a musí mať jasný účel a pravidlá. Zapíšte si, čo sa sleduje, ako ste boli informovaní a aký to má dopad; odbory preveria ďalší postup.', contact: true },
  { keywords: /nadriaden|manažér|vedenie|ignor|neodpoved|komunikácia/, answer: 'Uchovajte si vecnú komunikáciu a doklad o doručení. Pri pracovnej téme pomáha stručne pomenovať problém, požadovaný výsledok a termín odpovede. Ak firma nereaguje, odbory môžu vec riešiť systémovo.', contact: true },
  { keywords: /kolektívna zmluva|kolektívne vyjednávanie|rokovanie/, answer: 'Kolektívna zmluva upravuje pracovné podmienky a záväzky medzi odbormi a zamestnávateľom. Formálny návrh začína kolektívne vyjednávanie; druhá strana naň spravidla odpovedá písomne do 30 dní, ak sa strany nedohodnú inak. Pre konkrétny stav rokovania kontaktujte odbory.', contact: true },
  { keywords: /štrajk|výluka/, answer: 'Štrajk aj výluka majú osobitný zákonný postup a podmienky. Odboráčik ich nevie posúdiť podľa jednej správy; s otázkou sa obráťte priamo na odbory.', contact: true },
  { keywords: /informácie o firme|hospodárenie|výsledky firmy|účtovníctv|tržby/, answer: 'Zástupcovia zamestnancov majú právo na zrozumiteľné a včasné informácie o hospodárskej a finančnej situácii zamestnávateľa a predpokladanom vývoji. Rozsah konkrétnych podkladov a dôvernosť treba riešiť s odbormi.', contact: true },
  { keywords: /zástupca|funkcionár|predseda odbor|ochrana funkcionár/, answer: 'Odboroví funkcionári majú pri výkone funkcie osobitné postavenie a ochranu. Presný postup závisí od ich mandátu a konkrétnej situácie, preto ho riešte priamo s odborovou organizáciou.', contact: true },
  { keywords: /agentúra|agentúrny zamestnanec|dočasné pridelenie/, answer: 'Pri agentúrnej práci treba rozlišovať agentúru, užívateľského zamestnávateľa a konkrétnu zmluvu. Pošlite odborom, kto je váš zamestnávateľ, kde pracujete a čo sa stalo.', contact: true },
  { keywords: /školenie|zaškolenie|kvalifik|vzdelávanie/, answer: 'Pri školení je dôležité, či ide o povinnosť pre výkon práce, kto ho nariadil, kedy prebiehalo a ako bol evidovaný čas. Uložte si pozvánku alebo pokyn a obráťte sa na odbory pri spore.', contact: true },
  { keywords: /lehota|dokedy|termín|súd|žaloba/, answer: 'Konkrétne pracovnoprávne lehoty môžu byť krátke a závisia od typu veci a dátumu doručenia. Napište odborom ešte dnes, čo ste dostali a kedy; nespoliehajte sa len na všeobecnú odpoveď z chatu.', contact: true }
];
